spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
mybatis-flex:
  datasource:
    ds1:
      url: jdbc:dm://10.3.2.35:5236
      username: ALM
      password: 4WAi3Aqfo4pQ
  #    ds2:
  #      url: jdbc:dm://db:5236
  #      username: ALM
  #      password: ALM

  global-config:
    print-banner: on
  executor-type: batch # REUSE SIMPLE batch

#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:7080/xxl-job-admin
#    accessToken: default_token
#    executor:
#      appname: alm-batch
#      address:
#      ip:
#      port: 9999
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30
#powerjob:
#  worker:
#    app-name: alm-batch
#    port: 37777
#    server-address: 10.3.2.29:7700 #127.0.0.1:7700,127.0.0.1:7701 集群
#    protocol: HTTP # 推荐使用 HTTP 协议 AKKA
#    store-strategy: disk # 持久化方式，可选MEMORY，默认 disk;MEMORY
#    max-appended-wf-context-length: 8192 # 单个任务追加的工作流上下文最大长度，超过这个长度的会被直接丢弃，默认值 8192
#    max-result-length: 81920 # 任务返回结果信息的最大长度，超过这个长度的信息会被截断，默认值 8192
#    max-heavyweight-task-num: 64 # 同时运行的重量级任务数量上限
#    max-lightweight-task-num: 1024 # 同时运行的轻量级任务数量上限

liteflow:
  rule-source: config/**/*.el.xml #规则文件路径
  #-----------------以下非必须-----------------
  #liteflow是否开启，默认为true
  enable: true
  #liteflow的banner打印是否开启，默认为true
  print-banner: true
  #zkNode的节点，只有使用zk作为配置源的时候才起作用，默认为/lite-flow/flow
  #zk-node: /lite-flow/flow
  #上下文的最大数量槽，默认值为1024
  slot-size: 1024
  #FlowExecutor的execute2Future的线程数，默认为64
  main-executor-works: 64
  #FlowExecutor的execute2Future的自定义线程池Builder，LiteFlow提供了默认的Builder
  main-executor-class: com.yomahub.liteflow.thread.LiteFlowDefaultMainExecutorBuilder
  #自定义请求ID的生成类，LiteFlow提供了默认的生成类
  request-id-generator-class: com.yomahub.liteflow.flow.id.DefaultRequestIdGenerator
  #并行节点的线程池Builder，LiteFlow提供了默认的Builder
  thread-executor-class: com.yomahub.liteflow.thread.LiteFlowDefaultWhenExecutorBuilder
  #异步线程最长的等待时间(只用于when)，默认值为15000
  when-max-wait-time: 15000
  #异步线程最长的等待时间(只用于when)，默认值为MILLISECONDS，毫秒
  when-max-wait-time-unit: MILLISECONDS
  #when节点全局异步线程池最大线程数，默认为16
  when-max-workers: 16
  #when节点全局异步线程池等待队列数，默认为512
  when-queue-limit: 512
  #是否在启动的时候就解析规则，默认为true
  parse-on-start: true
  #全局重试次数，默认为0
  retry-count: 0
  #是否支持不同类型的加载方式混用，默认为false
  support-multiple-type: false
  #全局默认节点执行器
  node-executor-class: com.yomahub.liteflow.flow.executor.DefaultNodeExecutor
  #是否打印执行中过程中的日志，默认为true
  print-execution-log: true
  #是否开启本地文件监听，默认为false
  enable-monitor-file: false
  #简易监控配置选项
  monitor:
    #监控是否开启，默认不开启
    enable-log: false
    #监控队列存储大小，默认值为200
    queue-limit: 200
    #监控一开始延迟多少执行，默认值为300000毫秒，也就是5分钟
    delay: 300000
    #监控日志打印每过多少时间执行一次，默认值为300000毫秒，也就是5分钟
    period: 300000


sftp:
  # 端口
  port: 22
  # 服务器地址
  host: 120.46.135.203
  # 账号
  username: root
  # 密码
  password: CCT20221108!@
  # 文件存储的根路径
  basePath: /data/upload/rpc
  # session连接超时时间
  sessionConnectTimeout: 30000
  # channel连接超时时间
  channelConnectedTimeout: 30000
  # 协议
  protocol: sftp